version: '3'

services:

  httpd:
    image: agaveplatform/apim_httpd:certbot
    ports:
      - "80:80"
      - "443:443"

  agaveclients:
    image: clients-api:latest
    # Uncomment the following line (and comment the build line just above) to build from source
    build:
      context: ../
    ports:
      - "8001:80"
    links:
      - apim
      - mysql
    environment:
      HOST_IP:

  agaveid:
    image: agaveplatform/agave_id:latest
    # Uncomment the following line (and comment the build line just above) to build from source
  #  build: ../
    ports:
      - "8000:80"
    links:
      - ldap
    environment:
      HOST_IP:

  apim:
    image: agaveplatform/apim19_base:0.3
    ports:
      - "9443:9443"
      - "8243:8243"
      - "6284:6284"
    links:
      - ldap
      - mysql

  ldap:
    image: agaveplatform/slapd:latest
    environment:
      - LDAP_DOMAIN=agaveplatform
      - LDAP_ORGANISATION="Agave"
      - LDAP_ROOTPASS=p@ssword
    ports:
      - "10389:389"

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
